### ISSUE TITLE
forecast vs. projection

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-fish-tools/fishdictionary#20]
I think we are doing projections because typically set catches at various values and fixed parameters at different states of nature and provide results for various scenarios. @nathanvaughan-NOAA I would like to hear your thoughts given you spoke up at the FIMS meeting about this.

**Comment by nathanvaughan-NOAA** [comment]
I agree 100% with you Kelli that projection is the best definition of what we do. I think the forecast term is commonly used because that is what it is called in SS3, at least for me. I also think this distinction has practical importance and has led to issues when presenting results to SSC and Council reviewers in the past. For example, we are not forecasting how much we expect fleets will actually catch in future years, we are projecting what the population biomass would be given fixed future catch, recruitment, parameter, and model structure assumptions and setting maximum quotas to ensure that population biomass is maintained above a desired minimum sustainable level.
